[package]
name = "spidero"
version = "0.1.0"
authors = ["gengteng <me@gteng.org>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
json5 = "0.2.2"

futures = "0.1"
tokio = "0.1"
reqwest = "0.9"

html5ever = "*"